### ISSUE TITLE
Not compatible in RTL mode

### ISSUE THREAD

**Issue by classiebit** [SSENSE/vue-carousel#473]
## Bug Report

**Current Behavior**
When the direction is RTL, it shows a blank white screen.

**Input Code and steps to reproduce**
- Just make the direction RTL

```html
<body dir="rtl">
```

**Solution**
```css

[dir=rtl] .VueCarousel-wrapper {
    direction: ltr;
}
[dir=rtl] .VueCarousel-slide {
    direction: rtl;
}

```
